### ISSUE TITLE
Feature request: Docker image

### ISSUE THREAD

**Issue by torokati44** [skx/sos#23]
I was looking for a replacement to MongoDB + GridFS in my Docker Swarm application, because it was too slow when storing 5-10 bigger (couple hundred MiB) blobs concurrently. SOS looks exactly like what I need.
I saw that you already have a couple of Docker images on Docker Hub. It would make using SOS a whole lot easier if it was also available from there.
(And a tiny dedicated Python client on PyPI would be the cherry on top, but given how simple the HTTP API is, using Requests should also be straightforward enough.)

**Comment by skx** [comment]
If somebody submitted a merge-request to contribute a Dockerfile, or two, I would probably accept it.

But I've mostly lost interest in Docker these days, and I think it would be hard to provide something generally useful.  The issue is that for _real_ testing you'd want to have multiple instances of the blob-server running - to test replication & etc.  Hard-wiring 4+ daemons, with persistent storage volumes would seem reasonable, with one public API server on the front.  But another user might only want to have two, or ten.

I think this is the kind of software where you want to test in a more "real" environment to get an idea of whether it would suit.  As things stand this software is pretty basic, and while I use it and believe it to be "OK" I'd worry that people might suddenly start trying to upload large data without doing real testing in advance - and adding a Dockerfile would encourage that.

**Comment by torokati44** [comment]
I guess you are right. I ended up [mis]using sos by directly accessing a single blob server anyway, at least for the time being. Mostly because it handles HEAD, and I don't need replication. (Kudos for documenting the "internal" API as well!) And seeing that my Dockerfile was literally three lines, there isn't much value in submitting it, especially considering that it can never be general enough. Thanks for your response!

**Comment by skx** [comment]
:)
